 

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.JOptionPane;

/**
 *
 * @author Nate
 */
public class BattlePanel extends javax.swing.JPanel {

    private Player p;
    private Enemy e;
    private int turncount = 0;

    /**
     * Creates new form BattlePanel
     */
    public BattlePanel(Player p, Enemy e) {
        this.p = p;
        this.e = e;
        initComponents();
        reset();
    }

    synchronized void done() {
        notifyAll();
    }

    public void waits1() {
        waits();
    }

    synchronized void waits() {
        try {
            wait();
        } catch (InterruptedException ex) {
        }
    }

    public void reset() {
        jLabel2.setText(e.toString());
        jLabel3.setText("HP: " + p.getCurrentHealth() + "/" + p.getHealth());
        jLabel4.setText("HP: " + e.getHealth());

        jLabel5.setText("Attack: " + p.getAttack());

        jLabel6.setText("Defense: " + p.getDefense());

        jLabel7.setText("Attack: " + e.getAttack());

        jLabel8.setText("Defense: " + e.getDefense());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel() {
            public void paintComponent(Graphics g) {
                Graphics2D g2 = (Graphics2D) g;
                g2.drawImage(p.getImage(), 0, 0, 150, 150, null);
            }
        };
        jPanel2 = new javax.swing.JPanel() {
            public void paintComponent(Graphics g) {
                Graphics2D g2 = (Graphics2D) g;
                g2.drawImage(e.getImage(), 0, 0, 150, 150, null);
            }
        };
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fleeButton = new javax.swing.JButton();
        attackButton = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 150, Short.MAX_VALUE));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 150, Short.MAX_VALUE));

        jPanel2.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 150, Short.MAX_VALUE));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 150, Short.MAX_VALUE));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Player");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Enemy");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("       ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("        ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("       ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("       ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("       ");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("       ");

        fleeButton.setText("Flee");
        fleeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fleeButtonActionPerformed(evt);
            }
        });

        attackButton.setText("Attack");
        attackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel1)
                .addComponent(fleeButton)
                .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(attackButton)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(129, 129, 129)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3)
                .addComponent(jLabel4)))
                .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel7)
                .addComponent(jLabel8)
                .addComponent(jLabel6)
                .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(fleeButton)
                .addComponent(attackButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
    }// </editor-fold>                        

    private void attackButtonActionPerformed(java.awt.event.ActionEvent evt) {
        int pbefore = p.getCurrentHealth();
        int ebefore = e.getHealth();
        int attackvalue = Battle.attack(p, e);
        int pafter = p.getCurrentHealth();
        int eafter = e.getHealth();
        int ploss = pbefore - pafter;
        int eloss = ebefore - eafter;
        turncount++;

        if (!(e instanceof Boss)) {
            JOptionPane.showMessageDialog(this, "You " + p.getAttackMessage()
                    + e.getName() + " for " + attackvalue + " "
                    + "damage." + "\n" + e.getName() + " deals "
                    + ploss + " damage to you");
        } else if (e instanceof Boss && attackvalue == -37) {
            attackvalue = ebefore - (eafter - ((Boss) (e)).getHealFactor());
            JOptionPane.showMessageDialog(this, "You " + p.getAttackMessage()
                    + e.getName() + " for " + attackvalue + " "
                    + "damage." + "\n" + e.getName() + " heals himself"
                    + " for  " + ((Boss) (e)).getHealFactor() + " health. Dangnabbit.");
        } else if (e instanceof Boss) {
            JOptionPane.showMessageDialog(this, "You " + p.getAttackMessage()
                    + e.getName() + " for " + attackvalue + " "
                    + "damage." + "\n" + e.getName() + ((Boss) e).getMess() + "for "
                    + ploss + " damage. Ouch.");
        }

        if (pafter <= 0) {
            JOptionPane.showMessageDialog(this, "You Died !");
            done();            
        }
        
        else if (e.isDead() && e instanceof Boss) {
            Battle.rewardPlayer(p, e);
            
            if (p.addExp(e.getExp())) {
                JOptionPane.showMessageDialog(this, "You level up!");
            }

            e.removeThisCharacter();
            JOptionPane.showMessageDialog(this, "With its final breath, the boss takes a piece of equipment "
            + "from you and crumbles to nothing with it. \nWHAT?!");
            JOptionPane.showMessageDialog(this,
                    "You beat the boss! Peace returns to the area.\nYou also pick up some new loot! Nice. ");
            done();
        }
        else if (e.isDead()) {
            p.addGold(e.getGold());

            if (p.addExp(e.getExp())) {
                JOptionPane.showMessageDialog(this, "You level up!");
            }

            e.removeThisCharacter();
            JOptionPane.showMessageDialog(this,
                    "You Win !\nYou get " + e.getGold() + " gold.");
            done();
        }
        
        else if (turncount > 15)
        {
            JOptionPane.showMessageDialog(this, "Bored and frustrated, you leave this fight and decide to return when you're stronger.");
            done();
        }
        reset();
    }

    private void fleeButtonActionPerformed(java.awt.event.ActionEvent evt) {
        int pbefore = p.getCurrentHealth();
        if (Battle.runAway(p, e)) {
            JOptionPane.showMessageDialog(this, "Success");
            done();
        } else {
            JOptionPane.showMessageDialog(this, "Flee fails.\nYou get hit for "
                    + (pbefore - p.getCurrentHealth()) + " damage.");
            if (p.getCurrentHealth() <= 0) {
                JOptionPane.showMessageDialog(this, "You Died !");
                done();
            }
        }
        reset();
    }
    // Variables declaration - do not modify                     
    private javax.swing.JButton attackButton;
    private javax.swing.JButton fleeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration                   
}
